spring:
  # sharding-jdbc配置
  shardingsphere:
    # 数据源配置
    datasource:
      names: ds1,ds2
      ds1:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
        jdbc-url: jdbc:mysql://localhost:3306/test?useUnicode=true&useSSL=true&characterEncoding=utf8
        username: root
        password: root
        max-total: 100
      ds2:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
        jdbc-url: jdbc:mysql://localhost:3306/dev?useUnicode=true&useSSL=true&characterEncoding=utf8
        username: root
        password: root
        max-total: 100